# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/richard/Projects/honest-profiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/richard/Projects/honest-profiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/richard/Projects/honest-profiler/CMakeFiles /home/richard/Projects/honest-profiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/richard/Projects/honest-profiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named honest-profiler-agent

# Build rule for target.
honest-profiler-agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 honest-profiler-agent
.PHONY : honest-profiler-agent

# fast build rule for target.
honest-profiler-agent/fast:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/build
.PHONY : honest-profiler-agent/fast

src/main/cpp/agent.o: src/main/cpp/agent.cpp.o
.PHONY : src/main/cpp/agent.o

# target to build an object file
src/main/cpp/agent.cpp.o:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/agent.cpp.o
.PHONY : src/main/cpp/agent.cpp.o

src/main/cpp/agent.i: src/main/cpp/agent.cpp.i
.PHONY : src/main/cpp/agent.i

# target to preprocess a source file
src/main/cpp/agent.cpp.i:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/agent.cpp.i
.PHONY : src/main/cpp/agent.cpp.i

src/main/cpp/agent.s: src/main/cpp/agent.cpp.s
.PHONY : src/main/cpp/agent.s

# target to generate assembly for a file
src/main/cpp/agent.cpp.s:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/agent.cpp.s
.PHONY : src/main/cpp/agent.cpp.s

src/main/cpp/circular_queue.o: src/main/cpp/circular_queue.cpp.o
.PHONY : src/main/cpp/circular_queue.o

# target to build an object file
src/main/cpp/circular_queue.cpp.o:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/circular_queue.cpp.o
.PHONY : src/main/cpp/circular_queue.cpp.o

src/main/cpp/circular_queue.i: src/main/cpp/circular_queue.cpp.i
.PHONY : src/main/cpp/circular_queue.i

# target to preprocess a source file
src/main/cpp/circular_queue.cpp.i:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/circular_queue.cpp.i
.PHONY : src/main/cpp/circular_queue.cpp.i

src/main/cpp/circular_queue.s: src/main/cpp/circular_queue.cpp.s
.PHONY : src/main/cpp/circular_queue.s

# target to generate assembly for a file
src/main/cpp/circular_queue.cpp.s:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/circular_queue.cpp.s
.PHONY : src/main/cpp/circular_queue.cpp.s

src/main/cpp/log_writer.o: src/main/cpp/log_writer.cpp.o
.PHONY : src/main/cpp/log_writer.o

# target to build an object file
src/main/cpp/log_writer.cpp.o:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/log_writer.cpp.o
.PHONY : src/main/cpp/log_writer.cpp.o

src/main/cpp/log_writer.i: src/main/cpp/log_writer.cpp.i
.PHONY : src/main/cpp/log_writer.i

# target to preprocess a source file
src/main/cpp/log_writer.cpp.i:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/log_writer.cpp.i
.PHONY : src/main/cpp/log_writer.cpp.i

src/main/cpp/log_writer.s: src/main/cpp/log_writer.cpp.s
.PHONY : src/main/cpp/log_writer.s

# target to generate assembly for a file
src/main/cpp/log_writer.cpp.s:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/log_writer.cpp.s
.PHONY : src/main/cpp/log_writer.cpp.s

src/main/cpp/processor.o: src/main/cpp/processor.cpp.o
.PHONY : src/main/cpp/processor.o

# target to build an object file
src/main/cpp/processor.cpp.o:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/processor.cpp.o
.PHONY : src/main/cpp/processor.cpp.o

src/main/cpp/processor.i: src/main/cpp/processor.cpp.i
.PHONY : src/main/cpp/processor.i

# target to preprocess a source file
src/main/cpp/processor.cpp.i:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/processor.cpp.i
.PHONY : src/main/cpp/processor.cpp.i

src/main/cpp/processor.s: src/main/cpp/processor.cpp.s
.PHONY : src/main/cpp/processor.s

# target to generate assembly for a file
src/main/cpp/processor.cpp.s:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/processor.cpp.s
.PHONY : src/main/cpp/processor.cpp.s

src/main/cpp/profiler.o: src/main/cpp/profiler.cpp.o
.PHONY : src/main/cpp/profiler.o

# target to build an object file
src/main/cpp/profiler.cpp.o:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/profiler.cpp.o
.PHONY : src/main/cpp/profiler.cpp.o

src/main/cpp/profiler.i: src/main/cpp/profiler.cpp.i
.PHONY : src/main/cpp/profiler.i

# target to preprocess a source file
src/main/cpp/profiler.cpp.i:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/profiler.cpp.i
.PHONY : src/main/cpp/profiler.cpp.i

src/main/cpp/profiler.s: src/main/cpp/profiler.cpp.s
.PHONY : src/main/cpp/profiler.s

# target to generate assembly for a file
src/main/cpp/profiler.cpp.s:
	$(MAKE) -f CMakeFiles/honest-profiler-agent.dir/build.make CMakeFiles/honest-profiler-agent.dir/src/main/cpp/profiler.cpp.s
.PHONY : src/main/cpp/profiler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... honest-profiler-agent"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... src/main/cpp/agent.o"
	@echo "... src/main/cpp/agent.i"
	@echo "... src/main/cpp/agent.s"
	@echo "... src/main/cpp/circular_queue.o"
	@echo "... src/main/cpp/circular_queue.i"
	@echo "... src/main/cpp/circular_queue.s"
	@echo "... src/main/cpp/log_writer.o"
	@echo "... src/main/cpp/log_writer.i"
	@echo "... src/main/cpp/log_writer.s"
	@echo "... src/main/cpp/processor.o"
	@echo "... src/main/cpp/processor.i"
	@echo "... src/main/cpp/processor.s"
	@echo "... src/main/cpp/profiler.o"
	@echo "... src/main/cpp/profiler.i"
	@echo "... src/main/cpp/profiler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

