package com.insightfullogic.honest_profiler.core.profiles.lean;

import com.insightfullogic.honest_profiler.core.parser.ThreadMeta;

public class ThreadInfo
{
    private final long id;
    private String name;

    public ThreadInfo(long id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public ThreadInfo(ThreadMeta meta)
    {
        this.id = meta.getThreadId();
        this.name = meta.getThreadName();
    }

    public String getName()
    {
        return name;
    }

    public ThreadInfo checkAndSetName(String name)
    {
        if (name != null && !name.isEmpty())
        {
            this.name = name;
        }
        return this;
    }

    public long getId()
    {
        return id;
    }

    @Override
    // Generated by Eclipse
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (id ^ (id >>> 32));
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    @Override
    // Generated by Eclipse
    public boolean equals(Object obj)
    {
        if (this == obj)
        {
            return true;
        }

        if (obj == null)
        {
            return false;
        }

        if (getClass() != obj.getClass())
        {
            return false;
        }

        ThreadInfo other = (ThreadInfo) obj;
        if (id != other.id)
        {
            return false;
        }

        if (name == null)
        {
            if (other.name != null)
            {
                return false;
            }
        }
        else if (!name.equals(other.name))
        {
            return false;
        }

        return true;
    }

}
