#!/bin/sh

set -eu

java_path=$(readlink -f $(which javac))
java_home=$(echo $java_path | sed 's/javac$//')
tools_path="$java_home/../lib/tools.jar"

java -cp $tools_path:honest-profiler.jar com.insightfullogic.honest_profiler.ports.console.ConsoleApplication $@
