#!/bin/sh

set -eu

java_path=`which java`
java_home=`echo $java_path | sed 's/....$//'`
tools_path="$java_home/../lib/tools.jar"

java -cp $tools_path:honest-profiler.jar com.insightfullogic.honest_profiler.delivery.javafx.JavaFXEntry
